export const servicesDb = [
    {
      id: 1,
      serviceName: 'Corte de cabello',
      duration: '30 minutos',
      color: '#3933',
    },
    {
      id: 2,
      serviceName: 'Arreglo de barba',
      duration: '30 minutos',
      color: '#723636',
    },
    {
      id: 3,
      serviceName: 'Color',
      duration: '30 minutos',
      color: '#4545',
    },
    {
      id: 4,
      serviceName: 'Corte y cover',
      duration: '45 minutos',
      color: '#606',
    },
    {
      id: 5,
      serviceName: 'Decoloración y corte',
      duration: '120 minutos',
      color: '#404',
    },
    {
      id: 6,
      serviceName: 'Tratamiento',
      duration: '30 minutos',
      color: '#404',
    },
    {
      id: 7,
      serviceName: 'Mechas',
      duration: '30 minutos',
      color: '#404',
    },
    {
      id: 8,
      serviceName: 'Peinado',
      duration: '30 minutos',
      color: '#FF5733',
    },
    {
      id: 9,
      serviceName: 'Recogido',
      duration: '60 minutos',
      color: '#33FF57',
    },
    {
      id: 10,
      serviceName: 'Depilación piernas enteras',
      duration: '30 minutos',
      color: '#5733FF',
    },
    {
      id: 11,
      serviceName: 'Depilación axilas',
      duration: '15 minutos',
      color: '#FF33A6',
    },
    {
      id: 12,
      serviceName: 'Depilación ingles',
      duration: '15 minutos',
      color: '#33FFA6',
    },
    {
      id: 13,
      serviceName: 'Depilación ingles enteras',
      duration: '20 minutos',
      color: '#A633FF',
    },
    {
      id: 14,
      serviceName: 'Depilación brazos',
      duration: '15 minutos',
      color: '#FF3333',
    },
    {
      id: 15,
      serviceName: 'Depilación oídos',
      duration: '10 minutos',
      color: '#33FF33',
    },
    {
      id: 16,
      serviceName: 'Depilación nasal',
      duration: '10 minutos',
      color: '#3333FF',
    },
    {
      id: 17,
      serviceName: 'Depilación pómulos',
      duration: '10 minutos',
      color: '#FF33FF',
    },
    {
      id: 18,
      serviceName: 'Depilación mentón',
      duration: '10 minutos',
      color: '#33FFFF',
    },
    {
      id: 19,
      serviceName: 'Manicura normal',
      duration: '30 minutos',
      color: '#FFFF33',
    },
    {
      id: 20,
      serviceName: 'Manicura semi-permanente',
      duration: '40 minutos',
      color: '#FF8C33',
    },
    {
      id: 21,
      serviceName: 'Manicura permanente',
      duration: '60 minutos',
      color: '#8CFF33',
    },
    {
      id: 22,
      serviceName: 'Pedicura normal',
      duration: '60 minutos',
      color: '#338CFF',
    },
    {
      id: 23,
      serviceName: 'Pedicura permanente',
      duration: '90 minutos',
      color: '#FF338C',
    },
    {
      id: 24,
      serviceName: 'Limpieza cutis',
      duration: '90 minutos',
      color: '#8C33FF',
    },
    {
      id: 25,
      serviceName: 'Tratamientos estética',
      duration: '60 minutos',
      color: '#FFC300',
    },
    {
      id: 26,
      serviceName: 'Masajes drenaje',
      duration: '90 minutos',
      color: '#DAF7A6',
    },
    {
      id: 27,
      serviceName: 'Masaje general',
      duration: '60 minutos',
      color: '#C70039',
    },
    {
      id: 28,
      serviceName: 'Moldeador pestañas',
      duration: '30 minutos',
      color: '#900C3F',
    },
    {
      id: 29,
      serviceName: 'Tinte cejas',
      duration: '15 minutos',
      color: '#581845',
    },
    {
      id: 30,
      serviceName: 'Cejas y labio superior',
      duration: '15 minutos',
      color: '#1C2833',
    },
    {
      id: 31,
      serviceName: 'Maquillaje',
      duration: '50 minutos',
      color: '#F7DC6F',
    }
];